// Auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > lib/database.types.ts
// Or generate manually in Supabase Dashboard → Settings → API → Generate Types

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string
          avatar_url: string | null
          role: 'buyer' | 'artist' | 'admin'
          bio: string | null
          location: string | null
          website: string | null
          instagram: string | null
          artist_name: string | null
          specialization: string | null
          years_experience: number | null
          total_sales: number
          rating: number
          verified: boolean
          bank_account_verified: boolean
          stripe_account_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['profiles']['Row']> & { id: string; email: string; full_name: string }
        Update: Partial<Database['public']['Tables']['profiles']['Row']>
      }
      artworks: {
        Row: {
          id: string
          artist_id: string
          category_id: string | null
          title: string
          description: string
          price: number
          currency: string
          medium: string
          width_cm: number | null
          height_cm: number | null
          year_created: number | null
          status: 'draft' | 'pending_review' | 'active' | 'sold' | 'archived'
          is_original: boolean
          is_print_available: boolean
          print_price: number | null
          images: string[]
          thumbnail: string
          tags: string[]
          certificate_id: string | null
          views: number
          wishlisted_count: number
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['artworks']['Row']> & {
          artist_id: string; title: string; description: string
          price: number; medium: string; thumbnail: string; images: string[]
        }
        Update: Partial<Database['public']['Tables']['artworks']['Row']>
      }
      auctions: {
        Row: {
          id: string
          artwork_id: string
          artist_id: string
          starting_price: number
          reserve_price: number | null
          current_bid: number
          bid_count: number
          status: 'upcoming' | 'active' | 'ended' | 'cancelled'
          starts_at: string
          ends_at: string
          winner_id: string | null
          winner_bid: number | null
          created_at: string
        }
        Insert: Partial<Database['public']['Tables']['auctions']['Row']> & {
          artwork_id: string; artist_id: string; starting_price: number
          ends_at: string
        }
        Update: Partial<Database['public']['Tables']['auctions']['Row']>
      }
      bids: {
        Row: {
          id: string
          auction_id: string
          bidder_id: string
          amount: number
          is_proxy: boolean
          max_proxy_amount: number | null
          created_at: string
        }
        Insert: { auction_id: string; bidder_id: string; amount: number; is_proxy?: boolean; max_proxy_amount?: number }
        Update: never
      }
      orders: {
        Row: {
          id: string
          buyer_id: string
          artwork_id: string
          auction_id: string | null
          amount: number
          currency: string
          status: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled'
          stripe_payment_intent_id: string | null
          shipping_address: Record<string, unknown>
          tracking_number: string | null
          is_gift: boolean
          gift_message: string | null
          is_print: boolean
          print_size: string | null
          invoice_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: Partial<Database['public']['Tables']['orders']['Row']> & {
          buyer_id: string; artwork_id: string; amount: number
        }
        Update: Partial<Database['public']['Tables']['orders']['Row']>
      }
      certificates: {
        Row: {
          id: string
          artwork_id: string
          artist_id: string
          buyer_id: string | null
          certificate_number: string
          image_hash: string | null
          blockchain_tx: string | null
          issued_at: string
          metadata: Record<string, unknown>
        }
        Insert: {
          artwork_id: string; artist_id: string; certificate_number: string
          issued_at?: string; metadata?: Record<string, unknown>
          buyer_id?: string; image_hash?: string
        }
        Update: Partial<Database['public']['Tables']['certificates']['Row']>
      }
      categories: {
        Row: {
          id: string
          name: string
          slug: string
          description: string | null
          parent_id: string | null
          created_at: string
        }
        Insert: { name: string; slug: string; description?: string; parent_id?: string }
        Update: Partial<Database['public']['Tables']['categories']['Row']>
      }
      wishlists: {
        Row: { id: string; user_id: string; artwork_id: string; created_at: string }
        Insert: { user_id: string; artwork_id: string }
        Update: never
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
